### ISSUE TITLE
ClientWebSocketOptions support

### ISSUE THREAD

**Issue by emceelovin** [unoplatform/Uno.Wasm.WebSockets#16]
System.Net.WebSockets.ClientWebSocket has a ClientWebSocketOptions property that has a RequestHeaders property. Would it be possible to add this in? the source code for this can be found here [ClientWebSocket.cs](https://referencesource.microsoft.com/#system/net/System/Net/WebSockets/ClientWebSocket.cs,4fdc5e5e02b58901,references)

**Comment by jeromelaban** [comment]
Thanks for the report. This repository is not evolving as the support for WebSockets is now included in the .NET runtime. Please use the official sockets support instead.

**Comment by emceelovin** [comment]
unless I'm missing something extremely obvious, regular websocket calls via dotnet do not work for me. i have to use this package.

**Comment by jeromelaban** [comment]
Regular WebSockets should be working properly. If you have an example of code that does not work, please open an discussion here: https://github.com/unoplatform/uno/discussions

<blockquote><img src="https://repository-images.githubusercontent.com/132453438/7fcbaf80-9f86-11e9-9d5c-1feea63c9a2e" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/uno">Discussions · unoplatform/uno</a></strong></div><div>Build Mobile, Desktop and WebAssembly apps with C# and XAML. Today. Open source and professionally supported. - Discussions · unoplatform/uno</div></blockquote>
